name:                newtype-talk-five
version:             0.1.0.0
github:              "konn/newtype-talk-five"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/newtype-talk-five#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- reflection
- containers
- vector

library:
  source-dirs: src

executables:
  newtype-talk-five-exe:
    main:                example.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - newtype-talk-five
